<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER không chứa {vars}',
  '$_SERVER variable' => 'Biến $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] phải giống đường dẫn của file khởi động',
  'APC extensions' => 'APC extensions',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Tất cả <a href="http://www.yiiframework.com/doc/api/#system.db">các lớp liên quan đến CSDL</a>',
  'DOM extensions' => 'DOM extensions',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Biến $_SERVER["REQUEST_URI"] hoặc $_SERVER["QUERY_STRING"] phải tồn tại.',
  'GD extensions' => 'GD extensions',
  'Mcrypt extensions' => 'Mcrypt extensions',
  'Memcache extensions' => 'Memcache extensions',
  'PCRE extensions' => 'PCRE extensions',
  'PDO MySQL extensions' => 'PDO MySQl extensions',
  'PDO PostgreSQL extensions' => 'PDO PostgreSQL extensions',
  'PDO SQLite extensions' => 'PDO SQLite extensions',
  'PDO extensions' => 'PDO extensions',
  'PHP 5.1.0 or higher is required.' => 'Phải có PHP 5.1.0 hoặc mới hơn',
  'PHP version' => 'Phiên bản PHP',
  'Reflection extensions' => 'Reflection extensions',
  'SOAP extensions' => 'SOAP extensions',
  'SPL extensions' => 'SPL extensions',
  'This is required if you are using MySQL database.' => 'Cần phải có nếu bạn dùng MySQL',
  'This is required if you are using PostgreSQL database.' => 'Cần phải có nếu bạn dùng PostgreSQL',
  'This is required if you are using SQLite database.' => 'Cần phải có nếu bạn dùng SQLite',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Không xác định được thông tin đường dẫn URL. Hãy kiểm tra đảm bảo $_SERVER["PATH_INFO"] (hoặc $_SERVER["PHP_SELF"] và $_SERVER["SCRIPT_NAME"]) có giá trị đúng.',
);
