<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER inneholder ikke {vars}',
  '$_SERVER variable' => '$_SERVER variabel',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] må være lik filbanen til startscriptet',
  'APC extensions' => 'APC-tillegg',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Alle <a href="http://www.yiiframework.com/doc/api/#system.db">DB-relaterte klasser</a>',
  'DOM extensions' => 'DOM-extensions',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '',
  'GD extensions' => 'GD-extensions',
  'Mcrypt extensions' => 'Mcrypt-extensions',
  'Memcache extensions' => 'Memcache-extensions',
  'PCRE extensions' => 'PCRE-extensions',
  'PDO MySQL extensions' => 'PDO MYSQL-extensions',
  'PDO PostgreSQL extensions' => 'PDO PostgreSQL-extensions',
  'PDO SQLite extensions' => 'PDO SQLite-extensions',
  'PDO extensions' => 'PDO-extensions',
  'PHP 5.1.0 or higher is required.' => 'PHP 5.1.0 eller nyere er påkrevet',
  'PHP version' => 'PHP-versjon',
  'Reflection extensions' => 'Reflection-extensions',
  'SOAP extensions' => 'SOAP-extensions',
  'SPL extensions' => 'SPL-extensions',
  'This is required by encrypt and decrypt methods.' => 'Dette kreves av kryptering- og dekrypteringsmetodene.',
  'This is required if you are using MySQL database.' => 'Dette kreves hvis du bruker en MySQL database.',
  'This is required if you are using PostgreSQL database.' => 'Dette kreves hvis du bruker en PostgreSQL database.',
  'This is required if you are using SQLite database.' => 'Dette kreves hvis du bruker en SQLite database.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Kunne ikke finne path info. Vennligst sjekk at $_SERVER["PATH_INFO"] (eller $_SERVER["PHP_SELF"] og $_SERVER["SCRIPT_NAME"]) inneholder riktige verdier.',
);
