<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Ctype extensions' => 'Розширення Ctype',
  'GD extensions with<br />FreeType support' => 'Розширення GD із<br />підтримкою FreeType',
  'GD installed<br />FreeType support not installed' => 'GD встановлено<br />підтримку FreeType не встановлено',
  'GD not installed' => 'GD не встановлено',
  'To use memcached set <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> to <code>true</code>.' => 'Щоб використовувати memcached встановіть <a href="http://www.yiiframework.com/doc/api/CMemCache#useMemcached-detail">CMemCache::useMemcached</a> значення <code>true</code>.',
  'GD extensions' => '@@Розширення GD@@',
  '$_SERVER does not have {vars}.' => 'Змінна $_SERVER не містить {vars}.',
  '$_SERVER variable' => 'Змінна $_SERVER.',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => 'Змінна $_SERVER["SCRIPT_FILENAME"] повинна відповідати шляху до файла вхідного скрипта.',
  'APC extensions' => 'Розширення APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Всі <a href="http://www.yiiframework.com/doc/api/#system.db">DB-класи</a>',
  'DOM extensions' => 'Розширення DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => 'Повинна існувати хоча б одна з серверних змінних: $_SERVER["REQUEST_URI"] або $_SERVER["QUERY_STRING"].',
  'Mcrypt extensions' => 'Розширення Mcrypt',
  'Memcache extensions' => 'Розширення Memcache',
  'PCRE extensions' => 'Розширення PCRE',
  'PDO MySQL extensions' => 'Розширення PDO MySQL',
  'PDO PostgreSQL extensions' => 'Розширення PDO PostgreSQL',
  'PDO SQLite extensions' => 'Розширення PDO SQLite',
  'PDO extensions' => 'Розширення PDO',
  'PHP 5.1.0 or higher is required.' => 'Необхідна версія РНР 5.1.0 або вище.',
  'PHP version' => 'Версія РНР',
  'Reflection extensions' => 'Розширення Reflection',
  'SOAP extensions' => 'Розширення SOAP',
  'SPL extensions' => 'Розширення SPL',
  'This is required by encrypt and decrypt methods.' => 'Це потрібно для роботи методів шифрування і дешифрування.',
  'This is required if you are using MySQL database.' => 'Це потрібно для роботи з БД MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Це потрібно для роботи з БД PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Це потрібно для роботи з БД SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' => 'Не вдалось отримати інформацію про URL-шлях. Будь ласка, перевірте чи містяться вірні значення у змінній $_SERVER["PATH_INFO"] (або $_SERVER["PHP_SELF"] і $_SERVER["SCRIPT_NAME"]).',
);
