<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '$_SERVER does not have {vars}.' => '$_SERVER no contiene {vars}',
  '$_SERVER variable' => 'variable de $_SERVER',
  '$_SERVER["SCRIPT_FILENAME"] must be the same as the entry script file path.' => '$_SERVER["SCRIPT_FILENAME"] debe ser igual a la ruta de entrada del script',
  'APC extensions' => 'Extensión APC',
  'All <a href="http://www.yiiframework.com/doc/api/#system.db">DB-related classes</a>' => 'Todas las <a href="http://www.yiiframework.com/doc/api/#system.db">clases relacionadas con DB</a>',
  'DOM extensions' => 'Extensión DOM',
  'Either $_SERVER["REQUEST_URI"] or $_SERVER["QUERY_STRING"] must exist.' => '$_SERVER["REQUEST_URI"] o $_SERVER["QUERY_STRING"] deben existir.',
  'GD extensions' => 'Extensión GD',
  'Mcrypt extensions' => 'Extensión Mcrypt',
  'Memcache extensions' => 'Extensión Memcache',
  'PCRE extensions' => 'Extensión PCRE',
  'PDO MySQL extensions' => 'Extensión PDO MySQL',
  'PDO PostgreSQL extensions' => 'Extension PDO PostgreSQL',
  'PDO SQLite extensions' => 'Extensión PDO SQLite',
  'PDO extensions' => 'Extensión PDO',
  'PHP 5.1.0 or higher is required.' => 'Requiere PHP 5.1.0 o superior',
  'PHP version' => 'Versión PHP',
  'Reflection extensions' => 'Extensión Reflection',
  'SOAP extensions' => 'Extensión SOAP',
  'SPL extensions' => 'Extensión SPL',
  'This is required if you are using MySQL database.' => 'Esto es requerido si se utiliza una base de datos MySQL.',
  'This is required if you are using PostgreSQL database.' => 'Esto es requerido si se utiliza una base de datos PostgreSQL.',
  'This is required if you are using SQLite database.' => 'Esto es requerido si se utiliza una base de datos SQLite.',
  'Unable to determine URL path info. Please make sure $_SERVER["PATH_INFO"] (or $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_NAME"]) contains proper value.' 
		=> 'No es posible determinar la ruta de información. Por favor asegúrese que $_SERVER["PATH_INFO"] o ($_SERVER["PHP_SELF"] y $_SERVER["SCRIPT_NAME"]) contenga/n un valor correcto.',
);
